# Generated by Django 3.0.6 on 2020-05-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_code', models.CharField(help_text='The code of the transfer college', max_length=15, primary_key=True, serialize=False)),
                ('college_name', models.CharField(help_text='The name of the transfer college', max_length=50)),
            ],
            options={
                'verbose_name': 'college',
                'verbose_name_plural': 'colleges',
                'db_table': 'colleges',
                'ordering': ['college_code'],
            },
        ),
        migrations.CreateModel(
            name='MTUCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtu_course_id', models.CharField(help_text='The id of the MTU course', max_length=50)),
                ('mtu_course_name', models.CharField(help_text='The Name of the MTU course', max_length=50)),
                ('mtu_subject', models.CharField(help_text='The subject of the MTU course', max_length=50)),
                ('mtu_credits', models.FloatField(blank=True, help_text='The amount of credits the MTU course is')),
            ],
            options={
                'verbose_name': 'MTUCourse',
                'verbose_name_plural': 'MTUCourses',
                'db_table': 'mtu_courses',
                'ordering': ['mtu_course_id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='The abbreviation of the transfer college state', max_length=2, unique=True)),
                ('state_name', models.CharField(help_text='The long name of the transfer college state', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
                'db_table': 'states',
                'ordering': ['state_code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_course_credit', models.FloatField(blank=True, help_text='The number of credits the transfer course is')),
                ('transfer_course_number', models.CharField(help_text='The course number of the transfer course', max_length=15)),
                ('mtu_equiv', models.ForeignKey(help_text='The MTU course associated with the transfer course', on_delete=django.db.models.deletion.CASCADE, related_name='mtu_equiv', to='course_gather.MTUCourse')),
                ('transfer_course_college_code', models.ForeignKey(help_text='The college that the course is at', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_course_college_code', to='course_gather.College')),
                ('transfer_course_state_code', models.ForeignKey(help_text='The state the course is located in', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_course_state_code', to='course_gather.State')),
            ],
            options={
                'verbose_name': 'transfer_course',
                'verbose_name_plural': 'transfer_courses',
                'db_table': 'transfer_courses',
                'ordering': ['transfer_course_number'],
            },
        ),
    ]
