#!/usr/bin/env bash
set -e # If anything fails the script fails


export SECRET_KEY='superfakesecretkey'
export DJANGO_SETTINGS_MODULE='course_gather.settings.local_settings'

python manage.py makemigrations
python manage.py migrate

coverage erase
coverage run manage.py test --with-coverage
coverage report
